#!/usr/bin/env bash

os_x=`uname -a | fgrep -i 'Darwin'`

#echo $os_x

if [ "$os_x" != "" ]; then
    brightness -d 0x4281002 -v 0.25
else
    for disp in `DISPLAY=:0 xrandr --verbose | grep '(normal' | cut -d' ' -f 1`; do
    DISPLAY=:0 xrandr --output $disp --display ":0" --brightness 0.2 || true
    done
fi

